<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>编号</th>
        <th>用户名</th>
        <th>昵称</th>
        <th>手机号</th>
        <th>站点</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>1,001</td>
        <td>Lorem</td>
        <td>ipsum</td>
        <td>dolor</td>
        <td>sit</td>
      </tr>
      <tr>
        <td>1,002</td>
        <td>amet</td>
        <td>consectetur</td>
        <td>adipiscing</td>
        <td>elit</td>
      </tr>
      <tr>
        <td>1,006</td>
        <td>nibh</td>
        <td>elementum</td>
        <td>imperdiet</td>
        <td>Duis</td>
      </tr>
    </tbody>
  </table>
</div>